### ISSUE TITLE
show_transectsum(transectocc, site = 'S3T10')

### ISSUE THREAD

**Issue by Gmangrove** [tbep-tech/tbeptools#29]
I think the y-axis on graph should go from 0 to 1.0 to capture all values

**Comment by fawda123** [comment]
@Gmangrove do you mean this figure?  Does it not already?
![image](https://user-images.githubusercontent.com/3086881/95194388-37abc600-07a3-11eb-9b30-16c7a39a31b9.png)

**Comment by Gmangrove** [comment]
I will swear it didn't before (bottom was cut off), but looking fine now
