### ISSUE TITLE
New question re graph below show_transectsum(transectocc, site = 'S3T10')

### ISSUE THREAD

**Issue by Gmangrove** [tbep-tech/tbeptools#30]
The years on the x-axis don't look aligned. The giveaway for me is 2020, which should be the last set of data.

**Comment by fawda123** [comment]
These were originally plotted to sample date, so the years on the x-axis were showing correctly but they looked offset since sampling occurs late summer/fall.  I changed it to plot exactly on the year.  562d7b8f9bba5ee74650a744e418fe6a0a32f164
