### ISSUE TITLE
Data analysis using current year

### ISSUE THREAD

**Issue by Gmangrove** [tbep-tech/tbeptools#31]
Is the data analysis pulling in data from the current year? This could be problematic since not all data is in. May want to exclude current year until fully incorporated (hopefully early Nov this year).

**Comment by fawda123** [comment]
Any plot that shows results across many transects has a default for the year range to only show data up to 2019 (e.g., https://tbep-tech.github.io/tbeptools/reference/anlz_transectave.html).  The plot functions that show results for a single transect pull all data, assuming that if the most recent data are provided then it shows a complete survey.
