### ISSUE TITLE
Seagrass - plotting 1 or 2 species

### ISSUE THREAD

**Issue by Gmangrove** [tbep-tech/tbeptools#33]
For this graphing section: show_transectavespp(transectocc)

Is there an option where the total frequency of occurrence can be omitted so the graph is scaled to a better level, because species like Halodule and Ruppia will often just get lost in the bottom of the graph.

**Comment by fawda123** [comment]
@Gmangrove yes, use the option `total = FALSE`

```
library(tbeptools)
transectocc <- anlz_transectocc(transect)
show_transectavespp(transectocc, total = F)
```
![image](https://user-images.githubusercontent.com/3086881/99827681-f3447180-2b27-11eb-9cfa-d0ef86d874b6.png)
