### ISSUE TITLE
Transect dashboard

### ISSUE THREAD

**Issue by Gmangrove** [tbep-tech/tbeptools#35]
Looking so good! Suggest changing title for Tab #2 to "Individual Transects"

**Comment by fawda123** [comment]
Thanks @Gmangrove done! https://github.com/tbep-tech/seagrasstransect-dash/commit/6144f16543eb09b848195f70a273550db9d6af17

Also, any future issues for the dashboard should go in that specific repo https://github.com/tbep-tech/seagrasstransect-dash/issues
