### ISSUE TITLE
add circle size meaning to legend in map

### ISSUE THREAD

**Issue by bbest** [tbep-tech/tbeptools#4]
On behalf Chris Anastasiou chris.anastasiou@swfwmd.state.fl.us, can you add a legend to indicate what size of circle in map means?

@fawda123 : yes, is indicative of amt of Chl for all years

![image](https://user-images.githubusercontent.com/2837257/64372196-4d731880-cff0-11e9-96b2-39ad204731fe.png)

**Comment by fawda123** [comment]
Point legends for size are currently unavailable: https://github.com/rstudio/leaflet/issues/316

However, I added a color ramp to show chlorophyll concentration or light attenuation based on the user selection (https://github.com/tbep-tech/wq-dash/commit/aa23b17a13ad52d36be511954d2bc18dc5acb66b): 

![image](https://user-images.githubusercontent.com/3086881/69498977-cda46e00-0ebb-11ea-9736-ed2e55378597.png)

Note that the app has now migrated to its own repository: https://github.com/tbep-tech/wq-dash
