### ISSUE TITLE
Develop function to provide salinity means for bay segments

### ISSUE THREAD

**Issue by Gmangrove** [tbep-tech/tbeptools#40]
Suggest adding functionality to view salinity data, similar to presentations on [https://shiny.tbeptech.org/wq-dash/], including annual & monthly means, data by segment...

**Comment by fawda123** [comment]
Closing this out since a prelim version is here: https://tbep-tech.github.io/SOB-figures/salinity-trends @Gmangrove if you have any other needs for this, please post an issue in this repo: https://github.com/tbep-tech/SOB-figures
