### ISSUE TITLE
include Nekton Index

### ISSUE THREAD

**Issue by bbest** [tbep-tech/tbeptools#5]
Working with @meagschrandtphd et al:
 See Tampa Bay Estuary Program Open Science Workshop September 5 -6, 2019:

- [Group Exercise - Nekton Index - Google Docs](https://docs.google.com/document/d/1n8nS0kgNc9al7pQFcQEm7bhKeKU4ShiiubiDHwBuKE4/edit)

![image](https://user-images.githubusercontent.com/2837257/64442424-c54b4c80-d09d-11e9-93bd-05fcedb84cb3.png)

**Comment by fawda123** [comment]
Initial version of TBNI finished and detailed here 5cb835a092abb9c9c2eee12996267ab2a82e2945, but need to add some more functionality
